### ISSUE TITLE
incorrect PID control

### ISSUE THREAD

**Issue by nilay994** [SRA-AVITRA/avitra_esp#1]
https://github.com/SRA-AVITRA/avitra_esp/blob/488bf4fef609df3e0a4299dc2b68873eaa7df24c/test/rpm_tuning/main/motor.c#L17

previous error should be updated at the completion of the loop. Currently KD means nothing. The term KD is multiplied with is always zero.

**Comment by shanks-d** [comment]
Oops...Will correct it right away
