### ISSUE TITLE
remove integral gain

### ISSUE THREAD

**Issue by nilay994** [SRA-AVITRA/avitra_esp#2]
https://github.com/SRA-AVITRA/avitra_esp/blob/488bf4fef609df3e0a4299dc2b68873eaa7df24c/test/rpm_tuning/main/motor.c#L19

No need of integral gain. Integral gains can be used only if you really really care about reaching the exact setpoint rpm to the decimal precision.

**Comment by shanks-d** [comment]
Okay, I'll remove the integral part.
